import Item from './Item'
import ItemsContainer from './ItemsContainer'

import './Item.css'

const MAX_LEGENDARY_ITEMS_WITH_BOOTS = 4
const MAX_LEGENDARY_ITEMS_WITHOUT_BOOTS = 5

var hasMythic = false
var hasBoots = false
var legendaryItems = []

function selectMythic(itemClicked){
    const items = document.getElementById(`Mythic-container`)

    for(let item of items.children){
        if(item.id != itemClicked){
            item.className = "item-not-selected"
        }
        else{
            item.className = "item-selected"
            hasMythic = true;
        }
    }
}

function selectLegendary(itemClicked){

    if(legendaryItems.includes(itemClicked)){
        removeLegendaryItem(itemClicked)
        return
    }

    if(legendaryItems.length == getMaxLegendaryItems()){
        return
    }

    legendaryItems.push(itemClicked)

    if(legendaryItems.length == getMaxLegendaryItems()){
        markSelectedLegendaryItems()
    }

    console.log(legendaryItems)
}

function removeLegendaryItem(itemClicked){
    if(!legendaryItems.includes(itemClicked)){
        return
    }

    let index = legendaryItems.indexOf(itemClicked)

    document.getElementById(itemClicked).className = "item-not-selected"

    if(index > -1){
        legendaryItems.splice(index, 1)
    }

    unselectAllLegendaryItems()
}

function markSelectedLegendaryItems(){
    const items = document.getElementById('Legendary-container')

    for(let item of items.children){
        if(legendaryItems.includes(item.id)){
            console.log("LegendaryItems DOES include: ", item.id)
            item.className = "item-selected"
        }
        else{
            item.className = "item-not-selected";
        }
    }
}

function unselectAllLegendaryItems(){
    const items = document.getElementById('Legendary-container')

    for(let item of items.children){
        item.className = "item item-legendary"
    }
}

function getMaxLegendaryItems(){
    if(hasMythic && hasBoots){
        return 4
    }

    if(!hasMythic && hasBoots){
        return 5
    }

    if(hasMythic && !hasBoots){
        return 5
    }

    if(!hasMythic && !hasBoots){
        return 6
    }
}

function selectBoots(itemClicked){

    //Cannot add boots if the user has a Mythic selected, and 5 legendaries already.
    //TODO: Add an alert explaining why the user can't click on the boots? Or maybe just grey them out?
    if(!hasBoots && hasMythic && legendaryItems.length == MAX_LEGENDARY_ITEMS_WITHOUT_BOOTS){
        return;
    }

    const items = document.getElementById(`boots-container`)

    for(let item of items.children){
        if(item.id != itemClicked){
            item.className = "item-not-selected"
        }
        else{
            item.className = "item-selected"
            hasBoots = true;
        }
    }
}


//TODO: Split up the item types further, into class types
//      IE: Under Mythic, have sections for Mage/Tank/Support/Etc
export default function ItemSelectField(props){

    const mythic = []
    const legendary = []

    itemList.map((item) => {
        if(item.type == 'Mythic'){
                mythic.push(item)
        }
        else if(item.type == 'Legendary'){
            legendary.push(item)
        }
    })

    const boots = itemList.map((item) => {
        if(item.type == "Boots"){
            return (
                <Item type="boots" name={item.name} img={item.img} onclick={selectBoots} classes={item.class}/>
            )
        }
    })


    return (
        <div style={{width:"50%", height:"50%", outline:"red 2px solid", overflow:"auto", display:"flex", flexDirection:"column", alignItems:"center"}}>
                <ItemsContainer type="Mythic" items={mythic} itemOnClick={selectMythic}/>
                <h2>Boots</h2>
                <div id="boots-container" style={{display:"flex", flexDirection:"row", flexWrap:"wrap", width:"70%", outline:"2px solid blue"}}>
                    {boots}
                </div>
                <ItemsContainer type="Legendary" items={legendary} itemOnClick={selectLegendary} />
        </div>
    )

}

const itemList = [
    {name: "Boots", id: "1001", type: "Boots", effect: "<mainText><stats><attention>25</attention> Move Speed</stats></mainText><br>", img: "1001.png"},
    {name: "Faerie Charm", id: "1004", type: "Starter", effect: "<mainText><stats><attention>50%</attention> Base Mana Regen</stats></mainText><br>", img: "1004.png"},
    {name: "Rejuvenation Bead", id: "1006", class: ["Tank", "Bruiser"], type: "Starter", effect: "<mainText><stats><attention>100%</attention> Base Health Regen</stats></mainText><br>", img: "1006.png"},
    {name: "Giant's Belt", id: "1011", type: "Epic", class: ["Tank", "Bruiser"], effect: "<mainText><stats><attention>350</attention> Health</stats></mainText><br>", img: "1011.png"},
    {name: "Cloak of Agility", id: "1018", type: "Starter", class: ["Assassin", "ADC"], effect: "<mainText><stats><attention>15%</attention> Critical Strike Chance</stats></mainText><br>", img: "1018.png"},
    {name: "Blasting Wand", id: "1026", type: "Starter", class: ["Mage"], effect: "<mainText><stats><attention>40</attention> Ability Power</stats></mainText><br>", img: "1026.png"},
    {name: "Sapphire Crystal", id: "1027", type: "Starter", class:["Mage"], effect: "<mainText><stats><attention>250</attention> Mana</stats></mainText><br>", img: "1027.png"},
    {name: "Ruby Crystal", id: "1028", type: "Starter", class: ["Tank", "Bruiser", "Mage"], effect: "<mainText><stats><attention>150</attention> Health</stats></mainText><br>", img: "1028.png"},
    {name: "Cloth Armor", id: "1029", type: "Starter", class: ["Tank", "Bruiser", "Mage"], effect: "<mainText><stats><attention>15</attention> Armor</stats></mainText><br>", img: "1029.png"},
    {name: "Chain Vest", id: "1031", type: "Epic", class: ["Tank", "Bruiser"], effect: "<mainText><stats><attention>40</attention> Armor</stats></mainText><br>", img: "1031.png"},
    {name: "Null-Magic Mantle", id: "1033", type: "Starter", class: ["Tank", "Bruiser"], effect: "<mainText><stats><attention>25</attention> Magic Resist</stats></mainText><br>", img: "1033.png"},
    {name: "Long Sword", id: "1036", type: "Starter", class: ["ADC", "Bruiser", "Assassin"], effect: "<mainText><stats><attention>10</attention> Attack Damage</stats></mainText><br>", img: "1036.png"},
    {name: "Pickaxe", id: "1037", type: "Starter", class: ["ADC", "Bruiser", "Assassin"], effect: "<mainText><stats><attention>25</attention> Attack Damage</stats></mainText><br>", img: "1037.png"},
    {name: "B. F. Sword", id: "1038", type: "Starter", class: ["ADC", "Assassin"], effect: "<mainText><stats><attention>40</attention> Attack Damage</stats></mainText><br>", img: "1038.png"},
    {name: "Obsidian Edge", id: "1040", type: "Starter", class: ["Jungle"], effect: "<mainText><stats></stats><li><passive>Sear:</passive> Damaging Monsters burns them over time.<li><passive>Auto Path:</passive> Smiting 5 times consumes this item upgrade your Attack-Smite, increasing its damage to monsters.<li><passive>Huntsman:</passive> Killing Large Monsters grants bonus experience.<li><passive>Recoup:</passive> Regen mana when in the Jungle or River. <br><br><rules><status>Consuming</status> this item grants all item effects permanently and increases Smite damage to monsters. If you have gained more gold from minions than jungle monsters, gold and experience from minions is heavily reduced. Healing is not reduced on AoE attacks. If two levels behind the average champion level of the game, monster kills grant bonus experience. </rules></mainText><br>", img: "1040.png"},
    {name: "Dagger", id: "1042", type: "Starter", class: ["ADC", "Bruiser", "Assassin"], effect: "<mainText><stats><attention>12%</attention> Attack Speed</stats></mainText><br>", img: "1042.png"},
    {name: "Recurve Bow", id: "1043", type: "Epic", class: ["ADC", "Bruiser", "Assassin"], effect: "<mainText><stats><attention>25%</attention> Attack Speed</stats><br><li><passive>Steeltipped:</passive> Attacks apply physical damage On-Hit.</mainText><br>", img: "1043.png"},
    {name: "Amplifying Tome", id: "1052", type: "Starter", class: ["Mage"], effect: "<mainText><stats><attention>20</attention> Ability Power</stats></mainText><br>", img: "1052.png"},
    {name: "Vampiric Scepter", id: "1053", type: "Epic", class: ["ADC", "Bruiser", "Assassin"], effect: "<mainText><stats><attention>15</attention> Attack Damage<br><attention>7%</attention> Life Steal</stats></mainText><br>", img: "1053.png"},
    {name: "Doran's Shield", id: "1054", type: "Starter", class: ["Starter"], effect: "<mainText><stats><attention>80</attention> Health</stats><br><li><passive>Focus:</passive> Attacks deal additional damage to minions.<li><passive>Recovery:</passive> Restores Health over time.<li><passive>Endure:</passive> Restores Health after taking damage from a champion, large jungle monster, or epic jungle monster. Restoration increases when you are low Health.<br><br><rules><passive>Endure</passive> 66% effective when owned by Ranged champions or when taking damage from area of effect or periodic damage sources.</rules></mainText><br>", img: "1054.png"},
    {name: "Doran's Blade", id: "1055", type: "Starter", class: ["Starter"], effect: "<mainText><stats><attention>8</attention> Attack Damage<br><attention>80</attention> Health</stats><br><li><passive>Warmonger:</passive> Gain Omnivamp.<br><br><rules>Omnivamp is only 33% effective when dealing area of effect damage or damage through pets.</rules></mainText><br>", img: "1055.png"},
    {name: "Doran's Ring", id: "1056", type: "Starter", class: ["Starter"], effect: "<mainText><stats><attention>15</attention> Ability Power<br><attention>70</attention> Health</stats><br><li><passive>Focus:</passive> Attacks deal additional damage to minions. <li><passive>Drain:</passive> Restore Mana every second. Damaging an enemy champion increases this amount. If you can't gain Mana, regenerate Health instead. </mainText><br>", img: "1056.png"},
    {name: "Negatron Cloak", id: "1057", type: "Epic", class: ["Tank"], effect: "<mainText><stats><attention>50</attention> Magic Resist</stats></mainText><br>", img: "1057.png"},
    {name: "Needlessly Large Rod", id: "1058", type: "Starter", class: ["Mage"], effect: "<mainText><stats><attention>60</attention> Ability Power</stats></mainText><br>", img: "1058.png"},
    {name: "Dark Seal", id: "1082", type: "Starter", class: ["Mage"], effect: "<mainText><stats><attention>15</attention> Ability Power<br><attention>40</attention> Health</stats><br><li><passive>Glory:</passive> Gain 2 stacks for a champion kill or 1 stack for an assist (up to 10 stacks total). Lose 5 stacks on death.<li><passive>Dread:</passive> Grants <scaleAP>4 Ability Power</scaleAP> per stack of <passive>Glory</passive>.<br><br><rules>Obtained <passive>Glory</passive> stacks are preserved between this item and <rarityLegendary>Mejai's Soulstealer</rarityLegendary>.</rules></mainText><br>", img: "1082.png"},
    {name: "Cull", id: "1083", type: "Starter", class: ["Starter"], effect: "<mainText><stats><attention>7</attention> Attack Damage</stats><br><li>Attacks restore Health per hit.<li><passive>Reap:</passive> Killing a lane minion grants <goldGain>1</goldGain> additional gold. Killing 100 lane minions grants an additional <goldGain>350</goldGain> bonus gold immediately and disables <passive>Reap</passive>.<br></mainText><br>", img: "1083.png"},
    {name: "Scorchclaw Pup", id: "1101", type: "Starter", class: ["Starter", "Jungle"], effect: "<mainText><stats></stats><li><passive>Jungle Companions:</passive> Summon an <font color='#DD2E2E'>Scorchclaw</font> to assist you in the jungle.<li><passive>Scorchclaw's Slash:</passive> When fully grown your companion periodically imbues your next damaging effect to <status>Slow</status> and <passive>damage</passive> enemy champions.</mainText><br>", img: "1101.png"},
    {name: "Gustwalker Hatchling", id: "1102", type: "Starter", class: ["Starter", "Jungle"], effect: "<mainText><stats></stats><li><passive>Jungle Companions:</passive> Summon a <font color='#38A8E8'>Gustwalker</font> to assist you while in the jungle.<li><passive>Gustwalker's Gait:</passive> When fully grown your companion grants <speed>Move Speed</speed> after entering brush or killing monsters.</mainText><br>", img: "1102.png"},
    {name: "Mosstomper Seedling", id: "1103", type: "Starter", class: ["Starter", "Jungle"], effect: "<mainText><stats></stats><li><passive>Jungle Companions:</passive> Summon a <font color='#1CA935'>Mosstomper</font> to assist you while in the jungle. <li><passive>Mosstomper's Courage:</passive> When fully grown your companion grants a <shield>permanent shield</shield> that regenerates either after killing monsters or out of combat. While the shield holds gain 20% Tenacity and Slow Resist.</mainText><br>", img: "1103.png"},
    {name: "Health Potion", id: "2003", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><active>Active - Consume:</active> Drink the potion to restore <healing>120 Health</healing> over 15 seconds.<br><br><rules>You may carry up to 5 Health Potions.</rules></mainText><br>", img: "2003.png"},
    {name: "Kircheis Shard", id: "2015", type: "Epic", class: ["ADC"], effect: "<mainText><stats><attention>15%</attention> Attack Speed</stats><br><li><passive>Energized:</passive> Moving and Attacking will generate an Energized Attack.<li><passive>Jolt:</passive> Energized Attacks gain additional magic damage.</mainText><br>", img: "2015.png"},
    {name: "Refillable Potion", id: "2031", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><active>Active - Consume:</active> Consumes a charge to restore <healing>100 Health</healing> over 12 seconds. Holds up to 2 charges and refills upon visiting the shop.</mainText><br>", img: "2031.png"},
    {name: "Corrupting Potion", id: "2033", type: "Legendary", class: ["Consumable"], effect: "<mainText><stats></stats><active>Active - Consume:</active> Consumes a charge to restore <healing>100 Health</healing> and <scaleMana>75 Mana</scaleMana> over 12 seconds. During this time, damaging Abilities and Attacks burn enemy champions for <magicDamage>15 (20 if you cannot gain Mana) magic damage</magicDamage> over 3 seconds. Holds up to 3 charges and refills upon visiting the shop.<br><br><rules>Corrupting damage is reduced to 50% when triggered by area of effect or periodic damage.</rules></mainText><br>", img: "2033.png"},
    {name: "Guardian's Horn", id: "2051", type: "Starter", class: ["ARAM"], effect: "<mainText><stats><attention>150</attention> Health</stats><br><li><passive>Recovery:</passive> Restores Health over time.<li><passive>Undaunted:</passive> Blocks damage from attacks and spells from champions.<li><passive>Legendary:</passive> This item counts as a <rarityLegendary>Legendary</rarityLegendary> item.</mainText><br>", img: "2051.png"},
    {name: "Control Ward", id: "2055", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><active>Active - Consume:</active> Places a powerful Control Ward that grants vision of the surrounding area. This device will also reveal <keywordStealth>Invisible</keywordStealth> traps, reveal <keywordStealth>Camouflaged</keywordStealth> enemies, and reveal (and disable) enemy Stealth Wards. <br><br><rules>You may carry up to 2 Control Wards. Control Wards do not disable other Control Wards.</rules></mainText><br>", img: "2055.png"},
    {name: "Shurelya's Battlesong", id: "2065", type: "Mythic", class: ["Support"], effect: "<mainText><stats><attention>40</attention> Ability Power<br><attention>200</attention> Health<br><attention>20</attention> Ability Haste<br><attention>100%</attention> Base Mana Regen</stats><br><br><active>Active -</active> <active>Inspire:</active> Grants nearby allies Move Speed.<li><passive>Motivate:</passive> Empowering or Protecting another ally Champion grants both allies Move Speed.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Ability Haste.<br></mainText><br>", img: "2065.png"},
    {name: "Elixir of Iron", id: "2138", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><active>Active - Consume:</active> Drink to gain <scaleHealth>300 Health</scaleHealth>, 25% Tenacity, and increased champion size for 3 minutes. While active, moving leaves a path behind that boosts allied champions' <speed>Move Speed by 15%</speed>.<br><br><rules>Drinking a different Elixir will replace the existing one's effects.</rules></mainText><br>", img: "2138.png"},
    {name: "Elixir of Sorcery", id: "2139", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><active>Active - Consume:</active> Drink to gain <scaleAP>50 Ability Power</scaleAP> and <scaleMana>15% Mana Regen</scaleMana> for 3 minutes. While active, damaging a champion or turret deals <trueDamage>25 bonus true damage</trueDamage> (5s cooldown).<br><br><rules>Champion level <attention>9</attention> or greater required to purchase. Elixir of Sorcery's true damage effect has no cooldown when attacking turrets. Drinking a different Elixir will replace the existing one's effects.</rules></mainText><br>", img: "2139.png"},
    {name: "Elixir of Wrath", id: "2140", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><active>Active - Consume:</active> Drink to gain <scaleAD>30 Attack Damage</scaleAD> and <lifeSteal>12% Physical Vamp</lifeSteal> (against champions) for 3 minutes.<br><br><rules>Drinking a different Elixir will replace the existing one's effects.</rules></mainText><br>", img: "2140.png"},
    {name: "Stopwatch", id: "2420", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><active>Active -</active> <active>Stasis:</active> Use one time only to become <status>Invulnerable</status> and <status>Untargetable</status> for 2.5 seconds, but are prevented from taking any other actions during this time (transforms into a <rarityGeneric>Broken Stopwatch</rarityGeneric>).</mainText><br>", img: "2420.png"},
    {name: "Broken Stopwatch", id: "2421", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><br><li><passive>Shattered Time:</passive> Stopwatch is broken, but can still be upgraded.<br><br><rules>After breaking one Stopwatch, the shopkeeper will only sell you <rarityGeneric>Broken Stopwatches.</rarityGeneric></rules></mainText><br>", img: "2421.png"},
    {name: "Evenshroud", id: "3001", type: "Mythic", class: ["Support"], effect: "<mainText><stats><attention>200</attention> Health<br><attention>20</attention> Ability Haste<br><attention>30</attention> Armor<br><attention>30</attention> Magic Resist</stats><br><li><passive>Coruscation:</passive> After <status>Immobilizing</status> champions or being <status>Immobilized</status>, cause that target and all nearby enemy Champions to take increased damage.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items <attention> Armor and Magic Resist</attention></mainText><br>", img: "3001.png"},
    {name: "Archangel's Staff", id: "3003", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>70</attention> Ability Power<br><attention>500</attention> Mana<br><attention>200</attention> Health<br><attention>10</attention> Ability Haste</stats><br><li><passive>Awe:</passive> Gain Ability Power equal to bonus Mana.<li><passive>Mana Charge:</passive> Strike a target with an Ability to consume a charge and gain 3 bonus Mana, doubled if the target is a champion. Grants a maximum of 360 Mana at which point this item transforms into <rarityLegendary>Seraph's Embrace</rarityLegendary>.<br><br><rules>Gain a new <passive>Mana Charge</passive> every 8 seconds (max 4).</rules></mainText><br>", img: "3003.png"},
    {name: "Manamune", id: "3004", type: "Legendary", class: ["ADC", "Assassin"], effect: "<mainText><stats><attention>35</attention> Attack Damage<br><attention>500</attention> Mana<br><attention>15</attention> Ability Haste</stats><br><li><passive>Awe:</passive> Gain bonus <scaleAD>Attack Damage equal to your max Mana</scaleAD>. <li><passive>Mana Charge:</passive> Strike a target with an Ability or Attack to consume a charge and gain <scaleMana>3 bonus Mana</scaleMana>, doubled if the target is a champion. Grants a maximum of 360 Mana at which point this item transforms into <rarityLegendary>Muramana</rarityLegendary>.<br><br><rules>Gain a new <passive>Mana Charge</passive> every 8 seconds (max 4).</rules></mainText><br>", img: "3004.png"},
    {name: "Berserker's Greaves", id: "3006", type: "Boots", class: ["Boots", "ADC"], effect: "<mainText><stats><attention>35%</attention> Attack Speed<br><attention>45</attention> Move Speed</stats></mainText><br>", img: "3006.png"},
    {name: "Boots of Swiftness", id: "3009", type: "Boots", class: ["Boots"], effect: "<mainText><stats><attention>60</attention> Move Speed</stats><br><li>The strength of movement slowing effects is reduced by 25%.</mainText><br>", img: "3009.png"},
    {name: "Chemtech Putrifier", id: "3011", type: "Legendary", class: ["Support"], effect: "<mainText><stats><attention>40</attention> Ability Power<br><attention>8%</attention> Heal and Shield Power<br><attention>100%</attention> Base Mana Regen<br><attention>15</attention> Ability Haste</stats><br><li><passive>Puffcap Toxin:</passive> Dealing damage applies <status>40% Grievous Wounds</status> to champions for 3 seconds.<br><br><rules><status>Grievous Wounds</status> reduces the effectiveness of Healing and Regeneration effects.</rules></mainText><br>", img: "3011.png"},
    {name: "Sorcerer's Shoes", id: "3020", type: "Boots", class: ["Boots", "Mage"], effect: "<mainText><stats><attention>18</attention> Magic Penetration<br><attention>45</attention> Move Speed</stats></mainText><br>", img: "3020.png"},
    {name: "Glacial Buckler", id: "3024", type: "Epic", class: ["Tank"], effect: "<mainText><stats><attention>20</attention> Armor<br><attention>250</attention> Mana<br><attention>10</attention> Ability Haste</stats></mainText><br>", img: "3024.png"},
    {name: "Guardian Angel", id: "3026", type: "Legendary", class: ["Tank"], effect: "<mainText><stats><attention>45</attention> Attack Damage<br><attention>40</attention> Armor</stats><br><li><passive>Saving Grace:</passive> Upon taking lethal damage, restores <healing>50% base Health</healing> and <scaleMana>30% max Mana</scaleMana> after 4 seconds of stasis (300s cooldown).</mainText><br>", img: "3026.png"},
    {name: "Infinity Edge", id: "3031", type: "Legendary", class: ["ADC"], effect: "<mainText><stats><attention>70</attention> Attack Damage<br><attention>20%</attention> Critical Strike Chance</stats><br><li><passive>Perfection:</passive> If you have at least 40% Critical Strike Chance, gain35% Critical Strike Damage.</mainText><br>", img: "3031.png"},
    {name: "Mortal Reminder", id: "3033", type: "Legendary", class:["ADC"], effect: "<mainText><stats><attention>35</attention> Attack Damage<br><attention>30%</attention> Armor Penetration<br><attention>20%</attention> Critical Strike Chance</stats><br><li><passive>Sepsis:</passive> Dealing physical damage applies <status>40% Grievous Wounds</status> to enemy champions for 3 seconds.<br><br><rules><status>Grievous Wounds</status> reduces the effectiveness of Healing and Regeneration effects.</rules></mainText><br>", img: "3033.png"},
    {name: "Last Whisper", id: "3035", type: "Epic", class:["ADC"], effect: "<mainText><stats><attention>20</attention> Attack Damage<br><attention>18%</attention> Armor Penetration</stats></mainText><br>", img: "3035.png"},
    {name: "Lord Dominik's Regards", id: "3036", type: "Legendary", class: ["ADC"], effect: "<mainText><stats><attention>35</attention> Attack Damage<br><attention>20%</attention> Critical Strike Chance<br><attention>30%</attention> Armor Penetration</stats><br><li><passive>Giant Slayer:</passive> Deal bonus physical damage against champions with greater max Health than you.</mainText><br>", img: "3036.png"},
    {name: "Mejai's Soulstealer", id: "3041", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>20</attention> Ability Power<br><attention>100</attention> Health</stats><br><li><passive>Glory:</passive> Gain 4 stacks for a champion kill or 2 stacks for an assist (up to 25 stacks total). Lose 10 stacks on death.<li><passive>Dread:</passive> Grants <scaleAP>5 Ability Power</scaleAP> per stack of <passive>Glory</passive>. Gain <speed>10% Move Speed</speed> if you have at least 10 stacks.<br><br><rules>Obtained <passive>Glory</passive> stacks are preserved between this item and <rarityGeneric>Dark Seal</rarityGeneric>.</rules></mainText><br>", img: "3041.png"},
    {name: "Phage", id: "3044", type: "Epic", class:["Bruiser", "Tank"], effect: "<mainText><stats><attention>15</attention> Attack Damage<br><attention>200</attention> Health</stats><br><li><passive>Sturdy:</passive> After you deal physical damage to a champion, restore Health over time.<br><br><rules>Restoration reduced for Ranged users.</rules></mainText><br>", img: "3044.png"},
    {name: "Phantom Dancer", id: "3046", type: "Legendary", class:["ADC"], effect: "<mainText><stats><attention>20</attention> Attack Damage<br><attention>25%</attention> Attack Speed<br><attention>20%</attention> Critical Strike Chance<br><attention>7%</attention> Move Speed</stats><br><li><passive>Spectral Waltz:</passive> Attacks grant <status>Ghosting</status> and stacking increased Move Speed. In addition, Attacking 4 times causes Spectral Waltz to also grant Attack Speed.<br><br><rules><status>Ghosted</status> units ignore collision with other units.</rules></mainText><br>", img: "3046.png"},
    {name: "Plated Steelcaps", id: "3047", type: "Boots", class: ["Boots", "Tank"], effect: "<mainText><stats><attention>20</attention> Armor<br><attention>45</attention> Move Speed</stats><br><li>Reduces incoming damage from Attacks by 12%.</mainText><br>", img: "3047.png"},
    {name: "Zeke's Convergence", id: "3050", type: "Legendary", class: ["Support"], effect: "<mainText><stats><attention>250</attention> Health<br><attention>35</attention> Armor<br><attention>250</attention> Mana<br><attention>20</attention> Ability Haste</stats><br><br><active>Active -</active> <active>Conduit:</active> Designate an <attention>Accomplice</attention>.<br><li><passive>Convergence:</passive> After you <status>Immobilize</status> an enemy, your <attention>Accomplice's</attention> Attacks and Ability hits apply additional damage to that enemy.<br><br><rules>Champions can only be linked by one Zeke's Convergence at a time.</rules></mainText><br>", img: "3050.png"},
    {name: "Hearthbound Axe", id: "3051", type: "Epic", class: ["Bruiser", "Tank"], effect: "<mainText><stats><attention>15</attention> Attack Damage<br><attention>15%</attention> Attack Speed</stats><br><li><passive>Nimble:</passive> Attacking a unit grants Move Speed.</mainText><br>", img: "3051.png"},
    {name: "Sterak's Gage", id: "3053", type: "Legendary", class: ["Bruiser", "Tank"], effect: "<mainText><stats><attention>400</attention> Health</stats><br><li><passive>The Claws that Catch:</passive> Gain base AD as bonus Attack Damage.<li><passive>Lifeline:</passive> Upon taking damage that would reduce your Health below 30%, gain a Shield, decaying over time.</mainText><br>", img: "3053.png"},
    {name: "Sheen", id: "3057", type: "Starter", class:["Mage", "ADC", "Bruiser", "Assassin"], effect: "<mainText><stats></stats><li><passive>Spellblade:</passive> After using an Ability, your next Attack is enhanced with additional damage.</mainText><br>", img: "3057.png"},
    {name: "Spirit Visage", id: "3065", type: "Legendary", class: ["Bruiser", "Tank"], effect: "<mainText><stats><attention>450</attention> Health<br><attention>50</attention> Magic Resist<br><attention>10</attention> Ability Haste<br><attention>100%</attention> Base Health Regen</stats><br><li><passive>Boundless Vitality:</passive> Increases all Healing and Shielding effectiveness on you.</mainText><br>", img: "3065.png"},
    {name: "Winged Moonplate", id: "3066", type: "Epic", class: ["Tank", "Bruiser"], effect: "<mainText><stats><attention>150</attention> Health</stats><br><li><passive>Flight:</passive> Grants <speed>5% Move Speed</speed>.</mainText><br>", img: "3066.png"},
    {name: "Kindlegem", id: "3067", type: "Epic", class: ["Tank", "Bruiser", "Mage"], effect: "<mainText><stats><attention>200</attention> Health<br><attention>10</attention> Ability Haste</stats></mainText><br>", img: "3067.png"},
    {name: "Sunfire Aegis", id: "3068", type: "Legendary", class: ["Tank"], effect: "<mainText><stats><attention>500</attention> Health<br><attention>50</attention> Armor</stats><br><li><passive>Immolate:</passive> Taking or dealing damage causes you to begin dealing <magicDamage> (15 + 1.75% bonus Health) magic damage</magicDamage> per second to nearby enemies (increased by 25% against minions) for 3 seconds. Damaging Champions or Epic Monsters with this effect adds a stack, increasing subsequent <passive>Immolate</passive> damage by 10% for 5 seconds (max stacks 6).<br></mainText><br>", img: "3068.png"},
    {name: "Tear of the Goddess", id: "3070", type: "Starter", class:["Mage", "Assassin", "ADC", "Bruiser", "Tank"], effect: "<mainText><stats><attention>240</attention> Mana</stats><br><li><passive>Focus:</passive> Attacks deal additional physical damage to Minions.<li><passive>Mana Charge:</passive> Strike a target with an Ability to consume a charge and gain <scaleMana>3 bonus Mana</scaleMana>, doubled if the target is a champion. Grants a maximum of 360 Mana.<br><br><rules>Gain a new <passive>Mana Charge</passive> every 8 seconds (max 4).</rules></mainText><br>", img: "3070.png"},
    {name: "Black Cleaver", id: "3071", type: "Legendary", class: ["Assassin", "Bruiser"], effect: "<mainText><stats><attention>50</attention> Attack Damage<br><attention>400</attention> Health<br><attention>30</attention> Ability Haste</stats><br><li><passive>Carve:</passive> Dealing physical damage to a champion applies a stack of Armor reduction.<li><passive>Rage:</passive> Dealing physical damage to a champion grants Move Speed per stack of <unique>Carve</unique> on them.</mainText><br>", img: "3071.png"},
    {name: "Bloodthirster", id: "3072", type: "Legendary", class: ["Assassin", "ADC"], effect: "<mainText><stats><attention>55</attention> Attack Damage<br><attention>20%</attention> Critical Strike Chance<br><attention>15%</attention> Life Steal</stats><br><li><passive>Ichorshield:</passive> Life Steal from Attacks can now overheal you. Excess Health is stored as a Shield that decays slowly if you haven't dealt or taken damage.</mainText><br>", img: "3072.png"},
    {name: "Ravenous Hydra", id: "3074", type: "Legendary", class: ["ADC", "Assassin", "Bruiser"], effect: "<mainText><stats><attention>65</attention> Attack Damage<br><attention>25</attention> Ability Haste<br><attention>10%</attention> Life Steal</stats><br><li><passive>Cleave:</passive> Attacks and Abilities deal physical damage to other nearby enemies.<br><li><passive>Carnivorous:</passive> Gain AD whenever you kill a minion and 2 times that amount when you kill a Champion, Large Monster, or Siege Minion. Lose 60% of your stacks on death.<br><br></mainText><br>", img: "3074.png"},
    {name: "Thornmail", id: "3075", type: "Legendary", class: ["Tank"], effect: "<mainText><stats><attention>350</attention> Health<br><attention>70</attention> Armor</stats><br><li><passive>Thorns:</passive> When struck by an Attack, deal damage to the attacker and apply 40% <status>Grievous Wounds</status> if they are a champion.<br><br><rules><status>Grievous Wounds</status> reduces the effectiveness of Healing and Regeneration effects.</rules></mainText><br>", img: "3075.png"},
    {name: "Bramble Vest", id: "3076", type: "Epic", class: ["Tank"], effect: "<mainText><stats><attention>30</attention> Armor</stats><br><li><passive>Thorns:</passive> When struck by an Attack, deal damage to the attacker and apply 40% Grievous Wounds if they are a champion.<br><br><rules><status>Grievous Wounds</status> reduces the effectiveness of Healing and Regeneration effects.</rules></mainText><br>", img: "3076.png"},
    {name: "Tiamat", id: "3077", type: "Epic", class: ["ADC", "Bruiser", "Assassin"], effect: "<mainText><stats><attention>25</attention> Attack Damage</stats><br><li><passive>Cleave:</passive> Attacks deal physical damage to other nearby enemies. <br><br>Cleave does not trigger on structures.<br><br>Item performance differs for melee and ranged users.<br></mainText><br>", img: "3077.png"},
    {name: "Trinity Force", id: "3078", type: "Mythic", class: ["ADC", "Bruiser", "Assassin"], effect: "<mainText><stats><attention>35</attention> Attack Damage<br><attention>30%</attention> Attack Speed<br><attention>300</attention> Health<br><attention>20</attention> Ability Haste</stats><br><li><passive>Threefold Strike:</passive> Attacks grant Move Speed. If the target is a champion, increase your base Attack Damage, stacking.<li><passive>Spellblade:</passive> After using an Ability, your next Attack is enhanced with additional damage.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Attack Damage, Ability Haste, and Move Speed.</mainText><br>", img: "3078.png"},
    {name: "Warden's Mail", id: "3082", type: "Epic", class: ["Tank"], effect: "<mainText><stats><attention>40</attention> Armor</stats><br><li><passive>Rock Solid:</passive> Reduce incoming damage from Attacks.</mainText><br>", img: "3082.png"},
    {name: "Warmog's Armor", id: "3083", type: "Legendary", class: ["Tank"], effect: "<mainText><stats><attention>800</attention> Health<br><attention>10</attention> Ability Haste<br><attention>200%</attention> Base Health Regen</stats><br><li><passive>Warmog's Heart:</passive> If you have at least 1100 bonus Health, restore max Health per second if damage hasn't been taken within 6 seconds.</mainText><br>", img: "3083.png"},
    {name: "Heartsteel", id: "3084", type: "Mythic", class: ["Tank"], effect: "<mainText><stats><attention>800</attention> Health<br><attention>200%</attention> Base Health Regen<br><attention>20</attention> Ability Haste</stats><br><li><passive>Colossal Consumption:</passive> Charge up a powerful attack against a champion over 3s while within 700 range of them. The charged attack deals 125 + <scalehealth>6%</scalehealth> of your max Health as bonus physical damage, and grants you 10% of that amount as permanent max Health. (30s) cooldown per target.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items <attention>1%</attention> Increased Health & <attention>6%</attention> Champion Size.</mainText><br>", img: "3084.png"},
    {name: "Runaan's Hurricane", id: "3085", type: "Legendary", class: ["ADC"], effect: "<mainText><stats><attention>45%</attention> Attack Speed<br><attention>20%</attention> Critical Strike Chance<br><attention>7%</attention> Move Speed</stats><br><li><passive>Wind's Fury:</passive> When Attacking, bolts are fired at up to 2 enemies near the target. Bolts apply On-Hit effects and can Critically Strike.<br><br><rules>Item is for Ranged champions only.</rules></mainText><br>", img: "3085.png"},
    {name: "Zeal", id: "3086", type: "Epic", class: ["ADC"], effect: "<mainText><stats><attention>18%</attention> Attack Speed<br><attention>15%</attention> Critical Strike Chance</stats><br><li><passive>Zealous:</passive> Gain <speed>7% Move Speed</speed>.</mainText><br>", img: "3086.png"},
    {name: "Rabadon's Deathcap", id: "3089", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>120</attention> Ability Power</stats><br><li><passive>Magical Opus:</passive> Increases your total <scaleAP>Ability Power by 35%</scaleAP>.</mainText><br>", img: "3089.png"},
    {name: "Wit's End", id: "3091", type: "Legendary", class: ["Bruiser", "ADC"], effect: "<mainText><stats><attention>40</attention> Attack Damage<br><attention>40%</attention> Attack Speed<br><attention>40</attention> Magic Resist</stats><br><li><passive>Fray:</passive> Attacks apply magic damage On-Hit and grant Move Speed.</mainText><br>", img: "3091.png"},
    {name: "Rapid Firecannon", id: "3094", type: "Legendary", class: ["ADC"], effect: "<mainText><stats><attention>35%</attention> Attack Speed<br><attention>20%</attention> Critical Strike Chance<br><attention>7%</attention> Move Speed</stats><br><li><passive>Energized:</passive> Moving and Attacking will generate an Energized Attack.<li><passive>Sharpshooter:</passive> Your Energized Attack applies bonus damage. In addition, Energized attacks gain Attack Range.<br><br><rules>Attack Range cannot increase more than 150 units.</rules></mainText><br>", img: "3094.png"},
    {name: "Stormrazor", id: "3095", type: "Legendary", class: ["ADC"], effect: "<mainText><stats><attention>45</attention> Attack Damage<br><attention>15%</attention> Attack Speed<br><attention>20%</attention> Critical Strike Chance</stats><br><li><passive>Energized:</passive> Moving and Attacking will generate an Energized Attack.<li><passive>Paralyze:</passive> Your Energized Attack gains bonus magic damage. In addition, Energized Attacks slow enemies.<br></mainText><br>", img: "3095.png"},
    {name: "Lich Bane", id: "3100", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>85</attention> Ability Power<br><attention>15</attention> Ability Haste<br><attention>8%</attention> Move Speed</stats><br><li><passive>Spellblade:</passive> After using an Ability, your next Attack is enhanced with additional magic damage.</mainText><br>", img: "3100.png"},
    {name: "Banshee's Veil", id: "3102", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>80</attention> Ability Power<br><attention>45</attention> Magic Resist<br><attention>10</attention> Ability Haste</stats><br><li><passive>Annul:</passive> Grants a Spell Shield that blocks the next enemy Ability.<br><br><rules>Item cooldown is restarted if you take damage from champions before it is completed.</rules></mainText><br>", img: "3102.png"},
    {name: "Aegis of the Legion", id: "3105", type: "Epic", class: ["Tank"], effect: "<mainText><stats><attention>30</attention> Armor<br><attention>30</attention> Magic Resist<br><attention>10</attention> Ability Haste</stats></mainText><br>", img: "3105.png"},
    {name: "Redemption", id: "3107", type: "Legendary", class: ["Support"], effect: "<mainText><stats><attention>16%</attention> Heal and Shield Power<br><attention>200</attention> Health<br><attention>15</attention> Ability Haste<br><attention>100%</attention> Base Mana Regen</stats><br><br><active>Active -</active> <active>Intervention:</active> Target an area within. After 2.5 seconds, call down a beam of light to restore Health to allies and damage enemy champions.<br><br><rules>Item can be activated whilst dead. Damage and healing reduced by 50% if the target has recently been affected by another <active>Intervention</active>. Strength of level-scaling effects are based on the ally's level.</rules></mainText><br>", img: "3107.png"},
    {name: "Fiendish Codex", id: "3108", type: "Epic", class: ["Mage"], effect: "<mainText><stats><attention>35</attention> Ability Power<br><attention>10</attention> Ability Haste</stats></mainText><br>", img: "3108.png"},
    {name: "Knight's Vow", id: "3109", type: "Legendary", class: ["Support"], effect: "<mainText><stats><attention>400</attention> Health<br><attention>20</attention> Ability Haste<br><attention>200%</attention> Base Health Regen</stats><br><br><active>Active -</active> <active>Pledge:</active> Designate an ally who is <attention>Worthy</attention>..<br><li><passive>Sacrifice:</passive> While your <attention>Worthy</attention> ally is nearby, redirect damage they take to you and heal based on the damage dealt by your <attention>Worthy</attention> ally to Champions.<br></mainText><br>", img: "3109.png"},
    {name: "Frozen Heart", id: "3110", type: "Legendary", class: ["Tank"], effect: "<mainText><stats><attention>90</attention> Armor<br><attention>400</attention> Mana<br><attention>20</attention> Ability Haste</stats><br><li><passive>Winter's Caress:</passive> Reduces the <attackSpeed>Attack Speed</attackSpeed> of nearby enemies.<li><passive>Rock Solid:</passive> Reduce incoming damage from Attacks.</mainText><br>", img: "3110.png"},
    {name: "Mercury's Treads", id: "3111", type: "Boots", class: ["Boots", "Bruiser", "Tank"], effect: "<mainText><stats><attention>25</attention> Magic Resist<br><attention>45</attention> Move Speed<br><attention>30%</attention> Tenacity</stats><br><br><rules>Tenacity reduces the duration of <status>Stun</status>, <status>Slow</status>, <status>Taunt</status>, <status>Fear</status>, <status>Silence</status>, <status>Blind</status>, <status>Polymorph</status> and <status>Immobilizing</status> effects. It has no effect on <status>Airborne</status> or <status>Suppression</status>.</rules></mainText><br>", img: "3111.png"},
    {name: "Guardian's Orb", id: "3112", type: "Starter", class: ["ARAM"], effect: "<mainText><stats><attention>50</attention> Ability Power<br><attention>150</attention> Health</stats><br><li><passive>Recovery:</passive> Restores Mana over time. If you can't gain mana, restores Health instead.<li><passive>Legendary:</passive> This item counts as a <rarityLegendary>Legendary</rarityLegendary> item.</mainText><br>", img: "3112.png"},
    {name: "Aether Wisp", id: "3113", type: "Epic", class:["Mage"], effect: "<mainText><stats><attention>30</attention> Ability Power</stats><br><li><passive>Glide:</passive> Gain <speed>5% Move Speed</speed>.</mainText><br>", img: "3113.png"},
    {name: "Forbidden Idol", id: "3114", type: "Epic", class: ["Support"], effect: "<mainText><stats><attention>50%</attention> Base Mana Regen<br><attention>8%</attention> Heal and Shield Power</stats></mainText><br>", img: "3114.png"},
    {name: "Nashor's Tooth", id: "3115", type: "Legendary", class: ["Mage", "Bruiser"], effect: "<mainText><stats><attention>100</attention> Ability Power<br><attention>50%</attention> Attack Speed<br><attention>15</attention> Ability Haste</stats><br><li><passive>Icathian Bite:</passive> Attacks apply magic damage <OnHit>On-Hit</OnHit>.</mainText><br>", img: "3115.png"},
    {name: "Rylai's Crystal Scepter", id: "3116", type: "Legendary", class: ["Mage", "Bruiser"], effect: "<mainText><stats><attention>75</attention> Ability Power<br><attention>400</attention> Health</stats><br><li><passive>Rimefrost:</passive> Damaging Abilities <status>Slow</status> enemies.</mainText><br>", img: "3116.png"},
    {name: "Mobility Boots", id: "3117", type: "Boots", class: ["Boots"], effect: "<mainText><stats></stats><attention>25</attention> Move Speed <li>When out of combat for at least 5 seconds, increase this item's effect to <attention>115</attention>.</mainText><br>", img: "3117.png"},
    {name: "Winter's Approach", id: "3119", type: "Legendary", class: ["Tank", "Bruiser"], effect: "<mainText><stats><attention>400</attention> Health<br><attention>500</attention> Mana<br><attention>15</attention> Ability Haste</stats><br><li><passive>Awe:</passive> Gain bonus <scaleHealth>Health equal to Total Mana</scaleHealth>.<li><passive>Mana Charge:</passive> Strike a target with an Ability or Attack to consume a charge and gain <scaleMana>3 bonus Mana</scaleMana>, doubled if the target is a champion. Grants a maximum of 360 Mana at which point this item transforms into <rarityLegendary>Fimbulwinter</rarityLegendary>.<br><br><rules>Gain a new <passive>Mana Charge</passive> every 8 seconds (max 4).</rules></mainText><br>", img: "3119.png"},
    {name: "Executioner's Calling", id: "3123", type: "Epic", class: ["ADC", "Assassin", "Bruiser"], effect: "<mainText><stats><attention>15</attention> Attack Damage</stats><br><li><passive>Rend:</passive> Dealing physical damage applies <status>40% Grievous Wounds</status> to champions for 3 seconds. <br><br><rules><status>Grievous Wounds</status> reduces the effectiveness of Healing and Regeneration effects.</rules></mainText><br>", img: "3123.png"},
    {name: "Guinsoo's Rageblade", id: "3124", type: "Legendary", class: ["ADC", "Bruiser"], effect: "<mainText><stats><attention>45%</attention> Attack Speed<br><attention>20%</attention> Critical Strike Chance</stats><br><li><passive>Wrath:</passive> Your Critical Strike Chance is converted into <OnHit>On-Hit</OnHit> damage. Gain <physicalDamage>40</physicalDamage> <OnHit>On-Hit</OnHit> for each 20% Critical Strike Chance converted.<li><passive>Seething Strike:</passive> Every third Attack applies your On-Hit effects twice.<br><br><rules><passive>Wrath</passive> cannot benefit from more than 100% Critical Strike Chance. <passive>Wrath's</passive> On-Hit damage conversion is affected by Critical Strike damage modifiers. </rules></mainText><br>", img: "3124.png"},
    {name: "Caulfield's Warhammer", id: "3133", type: "Epic", class: ["ADC", "Assassin", "Bruiser"], effect: "<mainText><stats><attention>25</attention> Attack Damage<br><attention>10</attention> Ability Haste</stats></mainText><br>", img: "3133.png"},
    {name: "Serrated Dirk", id: "3134", type: "Epic", class: ["Assassin", "ADC"], effect: "<mainText><stats><attention>30</attention> Attack Damage</stats><br><li><passive>Gouge:</passive> Gain <scaleLethality>10 Lethality</scaleLethality>.</mainText><br>", img: "3134.png"},
    {name: "Void Staff", id: "3135", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>65</attention> Ability Power<br><attention>40%</attention> Magic Penetration</stats></mainText><br>", img: "3135.png"},
    {name: "Mercurial Scimitar", id: "3139", type: "Legendary", class: ["ADC", "Assassin"], effect: "<mainText><stats><attention>40</attention> Attack Damage<br><attention>20%</attention> Critical Strike Chance<br><attention>40</attention> Magic Resist</stats><br><br><active>Active -</active> <active>Quicksilver:</active> Remove all crowd control debuffs and gain Move Speed.</mainText><br>", img: "3139.png"},
    {name: "Quicksilver Sash", id: "3140", type: "Epic",  class: ["ADC", "Assassin", "Mage", "Bruiser", "Tank"], effect: "<mainText><stats><attention>30</attention> Magic Resist</stats><br><br><active>Active -</active> <active>Quicksilver:</active> Removes all crowd control debuffs (excluding <status>Airborne</status>).<br></mainText><br>", img: "3140.png"},
    {name: "Youmuu's Ghostblade", id: "3142", type: "Legendary", class: ["Assassin"], effect: "<mainText><stats><attention>55</attention> Attack Damage<br><attention>18</attention> Lethality<br><attention>15</attention> Ability Haste</stats><br><br><active>Active -</active> <active>Wraith Step:</active> Gain Move Speed and Ghosting.<br><li><passive>Haunt:</passive> Gain Move Speed out of combat.<br><br><rules><status>Ghosted</status> units ignore collision with other units.</rules></mainText><br>", img: "3142.png"},
    {name: "Randuin's Omen", id: "3143", type: "Legendary", class: ["Tank", "Bruiser"], effect: "<mainText><stats><attention>400</attention> Health<br><attention>60</attention> Armor</stats><br><br><active>Active -</active> <active>Humility:</active> <status>Slow</status> nearby enemies.<br><li><passive>Rock Solid:</passive> Reduce incoming damage from Attacks.<li><passive>Critical Resilience:</passive> Critical Strikes deal 20% less damage to you.</mainText><br>", img: "3143.png"},
    {name: "Hextech Alternator", id: "3145", type: "Epic", class: ["Mage"], effect: "<mainText><stats><attention>25</attention> Ability Power<br><attention>150</attention> Health</stats><br><li><passive>Revved:</passive> Damaging a champion deals additional damage.</mainText><br>", img: "3145.png"},
    {name: "Hextech Rocketbelt", id: "3152", type: "Mythic", class: ["Mage"], effect: "<mainText><stats><attention>90</attention> Ability Power<br><attention>6</attention> Magic Penetration<br><attention>250</attention> Health<br><attention>15</attention> Ability Haste</stats><br><br><active>Active -</active> <active>Supersonic:</active> Dash in target direction, unleashing an arc of magic missiles that deal damage. Then, gain Move Speed towards enemy champions.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Magic Penetration.</mainText><br>", img: "3152.png"},
    {name: "Blade of The Ruined King", id: "3153", type: "Legendary", class: ["Bruiser", "ADC", "Assassin"], effect: "<mainText><stats><attention>40</attention> Attack Damage<br><attention>25%</attention> Attack Speed<br><attention>8%</attention> Life Steal</stats><br><li><passive>Mist's Edge:</passive> Attacks apply physical damage based off of the target's current Health. <li><passive>Siphon:</passive> Attacking a champion 3 times deals magic damage and steals Move Speed.<br><br>Item performance differs for melee and ranged users.</mainText><br>", img: "3153.png"},
    {name: "Hexdrinker", id: "3155", type: "Epic", class: ["Bruiser", "ADC", "Assassin"], effect: "<mainText><stats><attention>25</attention> Attack Damage<br><attention>35</attention> Magic Resist</stats><br><li><passive>Lifeline:</passive> Upon taking magic damage that would reduce Health below 30%, gain a magic damage Shield.</mainText><br>", img: "3155.png"},
    {name: "Maw of Malmortius", id: "3156", type: "Legendary", class: ["Bruiser", "ADC", "Assassin"], effect: "<mainText><stats><attention>65</attention> Attack Damage<br><attention>50</attention> Magic Resist</stats><br><li><passive>Lifeline:</passive> Upon taking magic damage that would reduce Health below 30%, gain a magic damage Shield. When <passive>Lifeline</passive> triggers, gain Omnivamp until the end of combat.  </mainText><br>", img: "3156.png"},
    {name: "Zhonya's Hourglass", id: "3157", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>80</attention> Ability Power<br><attention>45</attention> Armor<br><attention>15</attention> Ability Haste</stats><br><br><active>Active -</active> <active>Stasis:</active> You become <status>Invulnerable</status> and <status>Untargetable</status> for 2.5 seconds, but are prevented from taking any other actions during this time.</mainText><br>", img: "3157.png"},
    {name: "Ionian Boots of Lucidity", id: "3158", type: "Boots", class: ["Boots"], effect: "<mainText><stats><attention>20</attention> Ability Haste<br><attention>45</attention> Move Speed</stats><br><li>Gain 12 Summoner Spell Haste.<br><br><flavorText>''This item is dedicated in honor of Ionia's victory over Noxus in the Rematch for the Southern Provinces on 10 December, 20 CLE.'</flavorText></mainText><br>", img: "3158.png"},
    {name: "Spear Of Shojin", id: "3161", type: "Legendary", class: ["Assassin"], effect: "<mainText><stats><attention>65</attention> Attack Damage<br><attention>300</attention> Health<br><attention>20</attention> Ability Haste</stats><br><li><passive>Dragonforce:</passive> Your Non-Ultimate spells gain (8 (+0.08 per 100 Bonus AD) | 6 (+0.06 per 100 Bonus AD)) Ability Haste, reduced to (4 (+0.04 per 100 Bonus AD) | 3 (+0.03 per 100 Bonus AD))) Ability Haste for Immobilizing spells.<li><passive>Exigency:</passive> Gain up to (0.15 | 0.1) increased move speed, based on your missing health (Maxed when below 33% Health).<br><br>Item performance differs for melee and ranged users.</mainText><br>", img: "3161.png"},
    {name: "Morellonomicon", id: "3165", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>90</attention> Ability Power<br><attention>200</attention> Health<br><attention>10</attention> Magic Penetration</stats><br><li><passive>Affliction:</passive> Dealing magic damage applies <status>40% Grievous Wounds</status> to enemy champions for 3 seconds.<br><br><rules><status>Grievous Wounds</status> reduces the effectiveness of Healing and Regeneration effects.</rules></mainText><br>", img: "3165.png"},
    {name: "Guardian's Blade", id: "3177", type: "Starter", class: ["ARAM"], effect: "<mainText><stats><attention>30</attention> Attack Damage<br><attention>150</attention> Health<br><attention>15</attention> Ability Haste</stats><br><li><passive>Legendary:</passive> This item counts as a <rarityLegendary>Legendary</rarityLegendary> item.</mainText><br>", img: "3177.png"},
    {name: "Umbral Glaive", id: "3179", type: "Legendary", class: ["Assassin"], effect: "<mainText><stats><attention>50</attention> Attack Damage<br><attention>10</attention> Lethality<br><attention>15</attention> Ability Haste</stats><br><li><passive>Blackout:</passive> When spotted by an enemy Ward, reveal traps and disable Wards around you. Your Attacks do increased damage to Wards.</mainText><br>", img: "3179.png"},
    {name: "Hullbreaker", id: "3181", type: "Legendary", class: ["Tank", "Bruiser"], effect: "<mainText><stats><attention>50</attention> Attack Damage<br><attention>400</attention> Health<br><attention>150%</attention> Base Health Regen</stats><br><br><li><passive>Boarding Party:</passive> While no allied champions are nearby you gain <scaleArmor>Armor</scaleArmor> and <scaleMR>Magic Resist</scaleMR> and Attacks deal increased damage to towers. Nearby large minions gain <scaleArmor>Armor</scaleArmor> and <scaleMR>Magic Resist</scaleMR> and increased damage to towers. <br><br><rules>Boarding Party's resistances decay over 3 seconds when an ally gets too close.</rules><br></mainText><br>", img: "3181.png"},
    {name: "Guardian's Hammer", id: "3184", type: "Starter", class: ["ARAM"], effect: "<mainText><stats><attention>25</attention> Attack Damage<br><attention>150</attention> Health<br><attention>7%</attention> Life Steal</stats><br><li><passive>Legendary:</passive> This item counts as a <rarityLegendary>Legendary</rarityLegendary> item.</mainText><br>", img: "3184.png"},
    {name: "Locket of the Iron Solari", id: "3190", type: "Mythic", class: ["Support"], effect: "<mainText><stats><attention>200</attention> Health<br><attention>20</attention> Ability Haste<br><attention>30</attention> Armor<br><attention>30</attention> Magic Resist</stats><br><br><active>Active -</active> <active>Devotion:</active> Grant nearby allies a <shield>Shield</shield>, decaying over time.<br><li><passive>Consecrate:</passive> Grant nearby allied champions Armor and <scaleMR>Magic Resist</scaleMR>. <br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Armor and Magic Resist increase to <passive>Consecrate</passive>.<br><br></mainText><br>", img: "3190.png"},
    {name: "Seeker's Armguard", id: "3191", type: "Epic",  class: ["Mage"], effect: "<mainText><stats><attention>30</attention> Ability Power<br><attention>15</attention> Armor</stats><br><li><passive>Witch's Path:</passive> Killing a unit grants <scaleArmor>0.5 Armor</scaleArmor> (max <scaleArmor>15</scaleArmor>).</mainText><br>", img: "3191.png"},
    {name: "Gargoyle Stoneplate", id: "3193", type: "Legendary", class: ["Tank"], effect: "<mainText><stats><attention>60</attention> Armor<br><attention>60</attention> Magic Resist<br><attention>15</attention> Ability Haste</stats><br><br><active>Active -</active> <active>Unbreakable:</active> Gain a Shield that decays and grow in size.<br><li><passive>Fortify:</passive> Taking damage from a champion grants a stack of <scaleArmor>bonus Armor</scaleArmor> and <scaleMR>bonus Magic Resist</scaleMR>.<br><br><rules>Max 5 stacks; 1 per champion.</rules></mainText><br>", img: "3193.png"},
    {name: "Spectre's Cowl", id: "3211", type: "Epic", class: ["Tank", "Bruiser"], effect: "<mainText><stats><attention>250</attention> Health<br><attention>25</attention> Magic Resist</stats><br><li><passive>Incorporeal:</passive> After taking damage from a champion, Regenerate Health.</mainText><br>", img: "3211.png"},
    {name: "Mikael's Blessing", id: "3222", type: "Legendary", class: ["Support"], effect: "<mainText><stats><attention>16%</attention> Heal and Shield Power<br><attention>50</attention> Magic Resist<br><attention>15</attention> Ability Haste<br><attention>100%</attention> Base Mana Regen</stats><br><br><active>Active -</active> <active>Purify:</active> Restore Health and Remove all crowd control debuffs (except <status>Knockups</status> and <status>Suppression</status>) from an ally champion.</mainText><br>", img: "3222.png"},
    {name: "Scarecrow Effigy", id: "3330", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><br><active>Active - Trinket:</active> Places an effigy that appears exactly as Fiddlesticks does to enemies. Stores up to a maximum of 2 charges.<br><br>Enemy champions approaching an effigy will activate it, causing the effigy to fake a random action, after which the effigy will fall apart.</mainText><br>", img: "3330.png"},
    {name: "Stealth Ward", id: "3340", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><active>Active - Trinket:</active> Place a Stealth Ward on the ground that is <keywordStealth>Invisible</keywordStealth> to enemies but grants your team vision of the surrounding area. Stores up to 2 Stealth Wards.</mainText><br>", img: "3340.png"},
    {name: "Farsight Alteration", id: "3363", type: "Starter", class: ["Trinket"], effect: "<mainText><stats></stats><active>Active - Trinket:</active> Reveals an area and places a visible, fragile Ward up to 4000 units away.</mainText><br>", img: "3363.png"},
    {name: "Oracle Lens", id: "3364", type: "Starter", class: ["Trinket"], effect: "<mainText><stats></stats><active>Active - Trinket:</active> Scans around you, warning against hidden enemy units, revealing invisible traps and revealing (and temporarily disabling) enemy Stealth Wards.</mainText><br>", img: "3364.png"},
    {name: "Ardent Censer", id: "3504", type: "Legendary", class: ["Support"], effect: "<mainText><stats><attention>60</attention> Ability Power<br><attention>8%</attention> Heal and Shield Power<br><attention>100%</attention> Base Mana Regen</stats><br><li><passive>Sanctify:</passive> Healing or Shielding another ally enhances you both, granting Attack Speed and magic damage <OnHit>On-Hit</OnHit>. <br></mainText><br>", img: "3504.png"},
    {name: "Essence Reaver", id: "3508", type: "Legendary", class: ["ADC"], effect: "<mainText><stats><attention>55</attention> Attack Damage<br><attention>20%</attention> Critical Strike Chance<br><attention>20</attention> Ability Haste</stats><br><li><passive>Spellblade:</passive> After using an Ability, your next Attack deals additional damage and restores Mana.</mainText><br>", img: "3508.png"},
    {name: "Kalista's Black Spear", id: "3599", type: "Starter", class: ["Consumable"], effect: "<mainText><stats></stats><active>Active - Consume:</active> Bind with an ally for the remainder of the game, becoming Oathsworn Allies. Oathsworn empowers you both while near one another.</mainText><br>", img: "3599.png"},
    {name: "Kalista's Black Spear", id: "3600", type: "Starter", class: ["Consumable"],effect: "<mainText><stats></stats><active>Active - Consume:</active> Bind with an ally for the remainder of the game, becoming Oathsworn Allies. Oathsworn empowers you both while near one another.<br><br><rules>Required to use <attention>Kalista's</attention> Ultimate Ability.</rules></mainText><br>", img: "3600.png"},
    {name: "Dead Man's Plate", id: "3742", type: "Legendary", class: ["Tank", "Bruiser"], effect: "<mainText><stats><attention>300</attention> Health<br><attention>45</attention> Armor<br><attention>5%</attention> Move Speed</stats><li><passive>Shipwrecker:</passive> While moving, build up  Move Speed. Your next Attack discharges built up Move Speed to deal damage. If dealt by a Melee champion at top speed, the Attack also <status>Slows</status> the target.<br><br><flavorText>''There's only one way you'll get this armor from me...'' - forgotten namesake</flavorText></mainText><br>", img: "3742.png"},
    {name: "Titanic Hydra", id: "3748", type: "Legendary",  class: ["Bruiser"],effect: "<mainText><stats><attention>30</attention> Attack Damage<br><attention>500</attention> Health</stats><br><li><passive>Colossus:</passive> Gain bonus <scaleAD>Attack Damage based off of bonus Health</scaleAD>.<li><passive>Cleave:</passive> Attacks apply additional damage <OnHit>On-Hit</OnHit>, creating a shockwave that deals damage to enemies behind the target.</mainText><br>", img: "3748.png"},
    {name: "Crystalline Bracer", id: "3801", type: "Epic", class: ["Tank"], effect: "<mainText><stats><attention>200</attention> Health<br><attention>100%</attention> Base Health Regen</stats></mainText><br>", img: "3801.png"},
    {name: "Lost Chapter", id: "3802", type: "Epic", class: ["Mage"], effect: "<mainText><stats><attention>40</attention> Ability Power<br><attention>300</attention> Mana<br><attention>10</attention> Ability Haste</stats><br><li><passive>Enlighten:</passive> Upon levelling up, restores <scaleMana>20% max Mana</scaleMana> over 3 seconds.</mainText><br>", img: "3802.png"},
    {name: "Catalyst of Aeons", id: "3803", type: "Epic", class: ["Mage"], effect: "<mainText><stats><attention>300</attention> Health<br><attention>300</attention> Mana</stats><br><li><passive>Eternity:</passive> Restore Mana equal to 7% of premitigation damage taken from champions, and Health equal to 25% of Mana spent, up to 20 Health per cast, per second.</mainText><br>", img: "3803.png"},
    {name: "Edge of Night", id: "3814", type: "Legendary", class: ["Assassin"], effect: "<mainText><stats><attention>50</attention> Attack Damage<br><attention>10</attention> Lethality<br><attention>325</attention> Health</stats><br><li><passive>Annul:</passive> Gain a Spell Shield that blocks the next enemy Ability.<br><br><rules>Item's cooldown is restarted if you take damage before it is completed.</rules></mainText><br>", img: "3814.png"},
    {name: "Spellthief's Edge", id: "3850", type: "Starter", class: ["Support"] ,effect: "<mainText><stats><attention>8</attention> Ability Power<br><attention>10</attention> Health<br><attention>25%</attention> Base Mana Regen<br><attention>2</attention> Gold Per 10 Seconds</stats><br><li><passive>Tribute:</passive> While nearby an ally champion, damaging Abilities and Attacks against champions or buildings grant 20 gold. This can occur up to 3 times every 36 seconds.<li><passive>Quest:</passive> Earn 500 gold from this item to transform it into <rarityGeneric>Frostfang</rarityGeneric>, gaining <active>Active -</active> <active>Warding</active>.<br><br><rules>This item grants reduced gold from minions if you kill excessive numbers of them.</rules></mainText><br>", img: "3850.png"},
    {name: "Steel Shoulderguards", id: "3854", type: "Starter", class: ["Support"], effect: "<mainText><stats><attention>3</attention> Attack Damage<br><attention>30</attention> Health<br><attention>50%</attention> Base Health Regen<br><attention>2</attention> Gold Per 10 Seconds</stats><li><passive>Spoils of War:</passive> While nearby an allied champion, Attacks execute minions below (50% for Melee Users | 30% for Ranged Users) of their max Health. Killing a minion grants the same kill gold to the nearest allied champion. These effects recharge every 35 seconds (Max 3 charges).<li><passive>Quest:</passive> Earn 500 gold from this item to transform it into <rarityGeneric>Runesteel Spaulders</rarityGeneric>, gaining <active>Active -</active> <active>Warding</active>.<br><br><rules>This item grants reduced gold from minions if you kill excessive numbers of them.</rules></mainText><br>", img: "3854.png"},
    {name: "Relic Shield", id: "3858", type: "Starter", class: ["Support"], effect: "<mainText><stats><attention>5</attention> Ability Power<br><attention>30</attention> Health<br><attention>50%</attention> Base Health Regen<br><attention>2</attention> Gold Per 10 Seconds</stats><li><passive>Spoils of War:</passive> While nearby an allied champion, Attacks execute minions below (50% for Melee Users | 30% for Ranged Users) of their max Health. Killing a minion grants the same kill gold to the nearest allied champion. These effects recharge every 35 seconds (Max 3 charges).<li><passive>Quest:</passive> Earn 500 gold from this item to transform it into <rarityGeneric>Targon's Buckler</rarityGeneric>, gaining <active>Active -</active> <active>Warding</active>.<br><br><rules>This item grants reduced gold from minions if you kill excessive numbers of them.</rules></mainText><br>", img: "3858.png"},
    {name: "Spectral Sickle", id: "3862", type: "Starter", class: ["Support"], effect: "<mainText><stats><attention>5</attention> Attack Damage<br><attention>10</attention> Health<br><attention>25%</attention> Base Mana Regen<br><attention>2</attention> Gold Per 10 Seconds</stats><br><li><passive>Tribute:</passive> While nearby an ally champion, damaging Abilities and Attacks against champions or buildings grant 20 gold. This can occur up to 3 times every 30 seconds.<li><passive>Quest:</passive> Earn 500 gold from this item to transform it into <rarityGeneric>Harrowing Crescent</rarityGeneric>, gaining <active>Active -</active> <active>Warding</active>.<br><br><rules>This item grants reduced gold from minions if you kill excessive numbers of them.</rules></mainText><br>", img: "3862.png"},
    {name: "Oblivion Orb", id: "3916", type: "Epic", class: ["Mage"], effect: "<mainText><stats><attention>30</attention> Ability Power</stats><br><li><passive>Cursed:</passive> Dealing magic damage applies <status>40% Grievous Wounds</status> to champions for 3 seconds.<br><br><rules><status>Grievous Wounds</status> reduces the effectiveness of Healing and Regeneration effects.</rules></mainText><br>", img: "3916.png"},
    {name: "Imperial Mandate", id: "4005", type: "Mythic", class: ["Support"], effect: "<mainText><stats><attention>40</attention> Ability Power<br><attention>200</attention> Health<br><attention>20</attention> Ability Haste<br><attention>100%</attention> Base Mana Regen</stats><br><li><passive>Coordinated Fire:</passive> Abilities that <status>Slow</status> or <status>Immobilize</status> a champion deal bonus damage and mark them. Ally champion damage detonates the mark, dealing additional damage and granting you both Move Speed. <br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Ability Power. <br></mainText><br>", img: "4005.png"},
    {name: "Force of Nature", id: "4401", type: "Legendary", class: ["Tank"], effect: "<mainText><stats><attention>350</attention> Health<br><attention>70</attention> Magic Resist<br><attention>5%</attention> Move Speed</stats><br><li><passive>Absorb:</passive> Taking <magicDamage>magic damage</magicDamage> from enemy Champions grants a stack of <attention>Steadfast</attention>. Enemy <status>Immobilizing</status> effects grant additional stacks.<li><passive>Dissipate:</passive> While at max stacks of <attention>Steadfast</attention>, take reduced magic damage and gain increased Move Speed.</mainText><br>", img: "4401.png"},
    {name: "The Golden Spatula", id: "4403", type: "Legendary", class: ["ARAM"], effect: "<mainText><stats><attention>70</attention> Attack Damage<br><attention>120</attention> Ability Power<br><attention>50%</attention> Attack Speed<br><attention>30%</attention> Critical Strike Chance<br><attention>250</attention> Health<br><attention>30</attention> Armor<br><attention>30</attention> Magic Resist<br><attention>250</attention> Mana<br><attention>20</attention> Ability Haste<br><attention>10%</attention> Move Speed<br><attention>10%</attention> Life Steal<br><attention>100%</attention> Base Health Regen<br><attention>100%</attention> Base Mana Regen</stats><br><li><passive>Doing Something:</passive> You are permanently On Fire!</mainText><br>", img: "4403.png"},
    {name: "Horizon Focus", id: "4628", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>100</attention> Ability Power<br><attention>150</attention> Health<br><attention>15</attention> Ability Haste</stats><br><li><passive>Hypershot:</passive> Damaging a champion with a non-targeted Ability at over 700 range or <status>Slowing or Immobilizing</status> them <keywordStealth>Reveals</keywordStealth> them and increases their damage taken from you.<br><br><rules>The Ability that triggers <passive>Hypershot</passive> also benefits from the damage increase. Pets and non-immobilizing traps do not trigger this effect. Only the initial placement of zone Abilities will trigger this effect. Distance is measured from the Ability cast position. </rules></mainText><br>", img: "4628.png"},
    {name: "Cosmic Drive", id: "4629", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>100</attention> Ability Power<br><attention>30</attention> Ability Haste<br><attention>5%</attention> Move Speed</stats><br><li><passive>Spelldance:</passive> Damaging a champion generates a stack of <speed>2.5% Move Speed</speed> every 1.5 seconds for the next 5 seconds up to <speed>10% Move Speed</speed>. At 4 stacks, gain an additional <speed>10% Move Speed</speed> (<speed>20% Move Speed</speed> total). Dealing damage refreshes this effect.<br> <br></mainText><br>", img: "4629.png"},
    {name: "Blighting Jewel", id: "4630", type: "Epic", class: ["Mage"], effect: "<mainText><stats><attention>25</attention> Ability Power<br><attention>13%</attention> Magic Penetration</stats></mainText><br>", img: "4630.png"},
    {name: "Verdant Barrier", id: "4632", type: "Epic", class: ["Mage"], effect: "<mainText><stats><attention>20</attention> Ability Power<br><attention>25</attention> Magic Resist</stats><br><li><passive>Adaptive:</passive> Killing a unit grants <scaleMR>0.3 Magic Resist</scaleMR> (max <scaleMR>9</scaleMR>). <br><br></mainText><br>", img: "4632.png"},
    {name: "Riftmaker", id: "4633", type: "Mythic", class: ["Mage"], effect: "<mainText><stats><attention>70</attention> Ability Power<br><attention>300</attention> Health<br><attention>15</attention> Ability Haste<br><attention>7%</attention> Omnivamp</stats><br><li><passive>Void Corruption:</passive> For each second damaging enemy champions, deal bonus damage. At maximum strength, the bonus damage is dealt as <trueDamage>true damage</trueDamage> instead. <br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Omnivamp and Ability Power.</mainText><br>", img: "4633.png"},
    {name: "Leeching Leer", id: "4635", type: "Epic", class: ["Mage"], effect: "<mainText><stats><attention>20</attention> Ability Power<br><attention>250</attention> Health<br><attention>5%</attention> Omnivamp</stats></mainText><br>", img: "4635.png"},
    {name: "Night Harvester", id: "4636", type: "Mythic", class: ["Mage"], effect: "<mainText><stats><attention>90</attention> Ability Power<br><attention>300</attention> Health<br><attention>25</attention> Ability Haste</stats><br><li><passive>Soulrend:</passive> Damaging a champion deals additional magic damage and grants you Move Speed.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Ability Haste.</mainText><br>", img: "4636.png"},
    {name: "Demonic Embrace", id: "4637", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>75</attention> Ability Power<br><attention>350</attention> Health</stats><br><li><passive>Azakana's Gaze:</passive> Dealing Ability damage burns enemies for max Health magic damage every second.<li><passive>Dark Pact:</passive> Gain <scaleHealth>bonus Health</scaleHealth> as <scaleAP>Ability Power</scaleAP>. </mainText><br>", img: "4637.png"},
    {name: "Watchful Wardstone", id: "4638", type: "Starter", class: ["Support"], effect: "<mainText><stats><attention>150</attention> Health<br><attention>10</attention> Ability Haste</stats><br><li><passive>Arcane Cache:</passive> This item can store up to 3 purchased Control Wards.<br><br>After completing the <keywordMajor>Support Quest</keywordMajor> and reaching Level 13, transforms into <rarityLegendary>Vigilant Wardstone</rarityLegendary>.<br></mainText><br>", img: "4638.png"},
    {name: "Bandleglass Mirror", id: "4642", type: "Epic", class: ["Support"], effect: "<mainText><stats><attention>20</attention> Ability Power<br><attention>10</attention> Ability Haste<br><attention>50%</attention> Base Mana Regen</stats></mainText><br>", img: "4642.png"},
    {name: "Crown of the Shattered Queen", id: "4644", type: "Mythic", class: ["Mage"], effect: "<mainText><stats><attention>70</attention> Ability Power<br><attention>250</attention> Health<br><attention>600</attention> Mana<br><attention>20</attention> Ability Haste</stats><br><li><passive>Divine Safeguard:</passive> You are <keywordMajor>Safeguarded</keywordMajor>, reducing incoming champion damage. <keywordMajor>Safeguard</keywordMajor> persists for 1.5 seconds after taking champion damage. <li><passive>Holy Gift:</passive> While <keywordMajor>Safeguarded</keywordMajor> and for 3 seconds after it is broken, gain  Ability Power. <br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Move Speed and Ability Power.</mainText><br>", img: "4644.png"},
    {name: "Shadowflame", id: "4645", type: "Legendary", class: ["Mage"], effect: "<mainText><stats><attention>100</attention> Ability Power<br><attention>200</attention> Health</stats><br><li><passive>Cinderbloom:</passive> Damage to champions benefits from additional <keywordStealth>Magic Penetration</keywordStealth> based on their current <scaleHealth>Health</scaleHealth>. If the target was recently affected by Shields, gain the maximum benefit against that target. </mainText><br>", img: "4645.png"},
    {name: "Ironspike Whip", id: "6029", type: "Epic", class: ["Bruiser"], effect: "<mainText><stats><attention>30</attention> Attack Damage</stats><br><br><active>Active -</active> <active>Crescent:</active> Deal damage to nearby enemies.</mainText><br>", img: "6029.png"},
    {name: "Silvermere Dawn", id: "6035", type: "Legendary", class: ["Bruiser"], effect: "<mainText><stats><attention>40</attention> Attack Damage<br><attention>300</attention> Health<br><attention>40</attention> Magic Resist</stats><br><br><active>Active -</active> <active>Quicksilver:</active> Remove all crowd control debuffs and gain Tenacity and Slow Resistance.</mainText><br>", img: "6035.png"},
    {name: "Death's Dance", id: "6333", type: "Legendary", class: ["Bruiser"], effect: "<mainText><stats><attention>55</attention> Attack Damage<br><attention>15</attention> Ability Haste<br><attention>45</attention> Armor</stats><br><li><passive>Ignore Pain:</passive> Damage taken is dealt to you over time instead.<li><passive>Defy:</passive> Champion takedowns cleanse <passive>Ignore Pain's</passive> remaining damage pool and restore Health over time.</mainText><br>", img: "6333.png"},
    {name: "Chempunk Chainsword", id: "6609", type: "Legendary", class: ["Bruiser", "Assassin"], effect: "<mainText><stats><attention>55</attention> Attack Damage<br><attention>250</attention> Health<br><attention>25</attention> Ability Haste</stats><br><li><passive>Hackshorn:</passive> Dealing physical damage applies 40% <status>Grievous Wounds</status> to enemy champions for 3 seconds.<br><br><rules><status>Grievous Wounds</status> reduces the effectiveness of Healing and Regeneration effects.</rules></mainText><br>", img: "6609.png"},
    {name: "Staff of Flowing Water", id: "6616", type: "Legendary", class: ["Support"], effect: "<mainText><stats><attention>50</attention> Ability Power<br><attention>8%</attention> Heal and Shield Power<br><attention>100%</attention> Base Mana Regen</stats><br><li><passive>Rapids:</passive> Healing or Shielding another ally grants you both Ability Power and Ability Haste.<br></mainText><br>", img: "6616.png"},
    {name: "Moonstone Renewer", id: "6617", type: "Mythic", class: ["Support"], effect: "<mainText><stats><attention>40</attention> Ability Power<br><attention>200</attention> Health<br><attention>20</attention> Ability Haste<br><attention>100%</attention> Base Mana Regen</stats><br><li><passive>Starlit Grace:</passive> When affecting champions with Attacks or Abilities in combat, restore Health to the most wounded nearby ally. Each second spent in combat with champions increases your Heal and Shield Power.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items an increase to <passive>Starlit Grace's</passive> Heal.<br><br></mainText><br>", img: "6617.png"},
    {name: "Goredrinker", id: "6630", type: "Mythic", class: ["Bruiser"], effect: "<mainText><stats><attention>55</attention> Attack Damage<br><attention>300</attention> Health<br><attention>20</attention> Ability Haste<br><attention>8%</attention> Omnivamp</stats><br><br><active>Active -</active> <active>Thirsting Slash:</active> Deal damage to nearby enemies. Restore Health for each champion hit.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Health and Ability Haste.</mainText><br>", img: "6630.png"},
    {name: "Stridebreaker", id: "6631", type: "Mythic", class: ["Bruiser"], effect: "<mainText><stats><attention>50</attention> Attack Damage<br><attention>20%</attention> Attack Speed<br><attention>300</attention> Health<br><attention>20</attention> Ability Haste</stats><br><br><active>Active -</active> <active>Halting Slash:</active> Deal damage to nearby enemies, <status>Slowing</status> them. Can be cast while moving.<br><li><passive>Heroic Gait:</passive> Dealing physical damage grants Move Speed.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Move Speed.</mainText><br>", img: "6631.png"},
    {name: "Divine Sunderer", id: "6632", type: "Mythic", class: ["Bruiser"], effect: "<mainText><stats><attention>40</attention> Attack Damage<br><attention>300</attention> Health<br><attention>20</attention> Ability Haste</stats><li><passive>Spellblade:</passive> After using an Ability, your next Attack is enhanced with additional damage <OnHit>On-Hit</OnHit>. If the target is a champion, also heal.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Armor Penetration and Magic Penetration.<br></mainText><br>", img: "6632.png"},
    {name: "Liandry's Anguish", id: "6653", type: "Mythic", class: ["Mage"], effect: "<mainText><stats><attention>80</attention> Ability Power<br><attention>600</attention> Mana<br><attention>20</attention> Ability Haste</stats><br><li><passive>Agony:</passive> Deal bonus magic damage to Champions based on the target's bonus Health.<li><passive>Torment:</passive> Dealing damage with Abilities causes enemies to burn over time.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Ability Haste.</mainText><br>", img: "6653.png"},
    {name: "Luden's Tempest", id: "6655", type: "Mythic", class: ["Mage"], effect: "<mainText><stats><attention>80</attention> Ability Power<br><attention>6</attention> Magic Penetration<br><attention>600</attention> Mana<br><attention>20</attention> Ability Haste</stats><br><li><passive>Echo:</passive> Damaging Abilities deal magic damage to the target and 3 nearby enemies and grants you Move Speed. Dealing ability damage to Champions reduces this item's cooldown.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Magic Penetration. </mainText><br>", img: "6655.png"},
    {name: "Everfrost", id: "6656", type: "Mythic", class: ["Mage"], effect: "<mainText><stats><attention>70</attention> Ability Power<br><attention>250</attention> Health<br><attention>600</attention> Mana<br><attention>20</attention> Ability Haste</stats><br><br><active>Active -</active> <active>Glaciate:</active> Deal damage in a cone, <status>Slowing</status> enemies hit. Enemies at the center of the cone are <status>Rooted</status> instead.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Ability Power. <br></mainText><br>", img: "6656.png"},
    {name: "Rod of Ages", id: "6657", type: "Mythic", class: ["Mage"], effect: "<mainText><stats><attention>60</attention> Ability Power<br><attention>400</attention> Health<br><attention>400</attention> Mana</stats><br><br>This item gains 20 Health, 20 Mana and 4 Ability Power every 60 seconds up to 10 times, for a maximum of 200 Health, 200 Mana,  and 40 Ability Power. Upon reaching max stacks, gain a level and all effects of Eternity are increased by 50%.<br><li><passive>Eternity:</passive> Restore Mana equal to 7% of premitigation damage taken from champions, and Health equal to 25% of Mana spent, up to 20 Health per cast, per second. For every 200 Health or Mana restored this way, gain <speed>35% Decaying Move Speed</speed> for 3 seconds.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items <attention>5 Ability Haste.</attention></mainText><br>", img: "6657.png"},
    {name: "Bami's Cinder", id: "6660", type: "Epic", class: ["Tank"], effect: "<mainText><stats><attention>300</attention> Health</stats><br><li><passive>Immolate :</passive> Taking or dealing damage causes you to begin dealing magic damage per second to nearby enemies (increased against minions and monsters).</mainText><br>", img: "6660.png"},
    {name: "Iceborn Gauntlet", id: "6662", type: "Mythic",  class: ["Tank"], effect: "<mainText><stats><attention>400</attention> Health<br><attention>50</attention> Armor<br><attention>20</attention> Ability Haste</stats><br><li><passive>Spellblade:</passive> After using an Ability, your next Attack is enhanced with additional damage and creates a frost field for 2.5s. Enemies that move across the field are <status>Slowed</status>. Your primary target is crippled, applying a 100% stronger slow on them and reducing their damage by 10% against you for 2.5s. (1.5s ).<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items <attention>50 Health</attention>, <attention>5%</attention> Tenacity, and <attention>5%</attention> Slow Resist.<br></mainText><br>", img: "6662.png"},
    {name: "Turbo Chemtank", id: "6664", type: "Legendary", class: ["Tank"], effect: "<mainText><stats><attention>500</attention> Health<br><attention>50</attention> Magic Resist<br><attention>10</attention> Ability Haste</stats><br><br><active>Active -</active> <active>Supercharged:</active> Grants Move Speed towards enemies or enemy turrets. Once near an enemy (or after 4 seconds) a shockwave is emitted that <status>Slows</status> nearby champions.</mainText><br>", img: "6664.png"},
    {name: "Jak'Sho, The Protean", id: "6665", type: "Mythic", class: ["Tank", "Bruiser"], effect: "<mainText><stats><attention>400</attention> Health<br><attention>30</attention> Armor<br><attention>30</attention> Magic Resist<br><attention>20</attention> Ability Haste</stats><br><li><passive>Voidborn Resilience:</passive> For each second in champion combat gain a stack granting <scaleArmor>Armor</scaleArmor> and <scaleMR>Magic Resist</scaleMR>, up to 8 stacks max. At max stacks become empowered, instantly draining enemies around you for magic damage, healing yourself, and increasing your bonus resist until end of combat.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items <attention> Armor and Magic Resist</attention>.</mainText><br>", img: "6665.png"},
    {name: "Radiant Virtue", id: "6667", type: "Mythic", class: ["Tank"], effect: "<mainText><stats><attention>400</attention> Health<br><attention>30</attention> Armor<br><attention>30</attention> Magic Resist<br><attention>20</attention> Ability Haste</stats><br><li><passive>Guiding Light:</passive> Upon casting your Ultimate you Transcend, increasing your Max Health. While Transcended you and allies heal over time.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Health.</mainText><br>", img: "6667.png"},
    {name: "Noonquiver", id: "6670", type: "Epic", class: ["ADC"], effect: "<mainText><stats><attention>30</attention> Attack Damage<br><attention>15%</attention> Attack Speed</stats><br><li><passive>Precision:</passive> Attacks deal additional damage to Minions and Monsters.</mainText><br>", img: "6670.png"},
    {name: "Galeforce", id: "6671", type: "Mythic", class: ["ADC"], effect: "<mainText><stats><attention>60</attention> Attack Damage<br><attention>20%</attention> Attack Speed<br><attention>20%</attention> Critical Strike Chance</stats><br><br><active>Active -</active> <active>Cloudburst:</active> Dash in target direction, firing three missiles at the lowest Health enemy near your destination. Deals damage, increased against low Health targets.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Move Speed.</mainText><br>", img: "6671.png"},
    {name: "Kraken Slayer", id: "6672", type: "Mythic", class: ["ADC"], effect: "<mainText><stats><attention>65</attention> Attack Damage<br><attention>25%</attention> Attack Speed<br><attention>20%</attention> Critical Strike Chance</stats><br><li><passive>Bring It Down:</passive> Every third Attack deals additional true damage.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Attack Speed.</mainText><br>", img: "6672.png"},
    {name: "Immortal Shieldbow", id: "6673", type: "Mythic", class: ["ADC"], effect: "<mainText><stats><attention>50</attention> Attack Damage<br><attention>20%</attention> Attack Speed<br><attention>20%</attention> Critical Strike Chance<br><attention>7%</attention> Life Steal</stats><br><li><passive>Lifeline:</passive> When taking damage that would reduce you below 30% Health, gain a Shield. In addition, gain Attack Damage.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Attack Damage and Health.</mainText><br>", img: "6673.png"},
    {name: "Navori Quickblades", id: "6675", type: "Legendary", class: ["ADC"], effect: "<mainText><stats><attention>60</attention> Attack Damage<br><attention>20%</attention> Critical Strike Chance<br><attention>20</attention> Ability Haste</stats><br><li><passive>Transcendence:</passive>  If you have at least 40% Critical Strike Chance, your Attacks reduce your non-Ultimate Ability cooldowns.<li><passive>Impermanence:</passive> Your abilities deal increased damage based on Critical Strike Chance.</mainText><br>", img: "6675.png"},
    {name: "The Collector", id: "6676", type: "Legendary", class: ["ADC", "Assassin"], effect: "<mainText><stats><attention>55</attention> Attack Damage<br><attention>20%</attention> Critical Strike Chance<br><attention>12</attention> Lethality</stats><br><li><passive>Death and Taxes:</passive> Dealing damage that would leave an enemy champion below 5% Health executes them. Champion kills grant an additional 25 gold.</mainText><br>", img: "6676.png"},
    {name: "Rageknife", id: "6677", type: "Epic", class: ["ADC", "Assassin"], effect: "<mainText><stats><attention>25%</attention> Attack Speed</stats><br><li><passive>Wrath:</passive> Your Critical Strike Chance is converted into <OnHit>On-Hit</OnHit> damage. Gain <physicalDamage>35</physicalDamage> <OnHit>On-Hit</OnHit> for each 20% Critical Strike Chance converted.</mainText><br>", img: "6677.png"},
    {name: "Duskblade of Draktharr", id: "6691", class: ["Assassin"], type: "Mythic", effect: "<mainText><stats><attention>60</attention> Attack Damage<br><attention>18</attention> Lethality<br><attention>20</attention> Ability Haste</stats><br><li><passive>Nightstalker:</passive> Attacking a champion deals additional damage. If dealt by a Melee champion, this Attack also <status>Slows</status> the target.  When a champion that you have damaged within the last 3 seconds dies, this cooldown is refreshed and you become <keywordStealth>Invisible</keywordStealth>.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Ability Haste and Move Speed.<br></mainText><br>", img: "6691.png"},
    {name: "Eclipse", id: "6692", type: "Mythic", class: ["Assassin"], effect: "<mainText><stats><attention>60</attention> Attack Damage<br><attention>12</attention> Lethality<br><attention>15</attention> Ability Haste</stats><br><br><li><passive>Ever Rising Moon:</passive> Hitting a champion with 2 separate Attacks or Abilities within 1.5 seconds deals additional damage, grants you Move Speed and a Shield.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Armor Penetration and Move Speed.</mainText><br>", img: "6692.png"},
    {name: "Prowler's Claw", id: "6693", type: "Mythic", class: ["Assassin"], effect: "<mainText><stats><attention>60</attention> Attack Damage<br><attention>18</attention> Lethality<br><attention>20</attention> Ability Haste</stats><br><br><active>Active -</active> <active>Sandswipe:</active> Dash through target enemy champion, dealing damage. You deal increased damage to the target.<br><br><rarityMythic>Mythic Passive:</rarityMythic> Grants all other <rarityLegendary>Legendary</rarityLegendary> items Lethality and Move Speed.</mainText><br>", img: "6693.png"},
    {name: "Serylda's Grudge", id: "6694", type: "Legendary", class: ["Assassin"], effect: "<mainText><stats><attention>45</attention> Attack Damage<br><attention>30%</attention> Armor Penetration<br><attention>20</attention> Ability Haste</stats><br><li><passive>Bitter Cold:</passive> Damaging Abilities <status>Slow</status> enemies.</mainText><br>", img: "6694.png"},
    {name: "Serpent's Fang", id: "6695", type: "Legendary", class: ["Assassin", "ADC"], effect: "<mainText><stats><attention>55</attention> Attack Damage<br><attention>12</attention> Lethality</stats><br><li><passive>Shield Reaver:</passive> Dealing damage to an enemy champion reduces any shields they gain. When you damage an enemy who is unaffected by Shield Reaver, reduce all shields on them.<br><br>Item performance differs for melee and ranged users.</mainText><br>", img: "6695.png"},
    {name: "Axiom Arc", id: "6696", type: "Legendary", class: ["Assassin"], effect: "<mainText><stats><attention>55</attention> Attack Damage<br><attention>18</attention> Lethality<br><attention>25</attention> Ability Haste</stats><br><li><passive>Flux:</passive> Whenever a Champion dies within 3 seconds of you having damaged them, refund 20% of your Ultimate Ability's total cooldown.</mainText><br>", img: "6696.png"},
    {name: "Anathema's Chains", id: "8001", type: "Legendary", class: ["Tank", "Support", "Bruiser"], effect: "<mainText><stats><attention>650</attention> Health<br><attention>20</attention> Ability Haste</stats><br><br><active>Active -</active> <active>Vow:</active> Choose a Nemesis to start building a Vendetta (90s).<br><li><passive>Vendetta:</passive> Take reduced damage from your Nemesis, increasing per Vendetta stack. You gain stacks over time, and reach the maximum number of stacks after 60 seconds.<li><passive>Vengeance:</passive> At maximum stacks, your Nemesis has reduced Tenacity while near you.<br><br><rules>Active can be cast while dead and at global range. Stacks reset upon choosing a new target. Cannot be cast for 15 seconds while in-combat with champions.</rules><br><br><flavorText>She swore to dedicate her life to his destruction. The gauntlets heard.</flavorText></mainText><br>", img: "8001.png"},
    {name: "Abyssal Mask", id: "8020", type: "Legendary", class: ["Tank"], effect: "<mainText><stats><attention>550</attention> Health<br><attention>300</attention> Mana<br><attention>40</attention> Magic Resist<br><attention>10</attention> Ability Haste</stats><br><li><passive>Eternity:</passive> Restore Mana equal to 7% of premitigation damage taken from champions, and Health equal to 25% of Mana spent, up to 20 Health per cast, per second.<li><passive>Unmake:</passive> <status>Curse</status> nearby enemy champions, reducing their Magic Resist. For each <status>Cursed</status> enemy, gain Magic Resist.</mainText><br>", img: "8020.png"},
]